# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='tv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepages.Tv'),
        ),
    ]
