# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0002_auto_20160221_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 24, 1, 34, 27, 568441, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
