# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0003_tv_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
