# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0004_auto_20160224_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
