# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0005_slide_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['index']},
        ),
    ]
