# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0006_auto_20160307_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='tv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='homepages.Tv'),
        ),
    ]
