# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0007_auto_20160308_2142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together=set([('index', 'tv')]),
        ),
    ]
