# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0007_auto_20160302_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['index']},
        ),
    ]
