# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0008_auto_20160308_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
