FORMAT: 1A
HOST: http://bchopson.apiary.io/

# Smart TV Content API

Smart TV Content API is an api that allows users to choose which
content to display on connected Smart TVs.

## TV Collection [/tvs]

### List All TVs [GET]

+ Response 200 (application/json)

        [
            {
                "id": "1",
                "slides": [
                    {
                        "url": "http://google.com",
                        "duration": 10
                    }, {
                        "url": "http://cs.armstrong.edu",
                        "duration": 20
                    }, {
                        "url": "http://armstrong.edu",
                        "duration": 10
                    }
                ]
            }
        ]

### Register a New TV [POST]

You may register a new TV endpoint here. Note that the TV will be
required to point to a specific URL on startup.

+ Request (application/json)

        {
            "slides": [
                {
                    "url": "http://google.com",
                    "duration": 10
                }, {
                    "url": "http://cs.armstrong.edu",
                    "duration": 20
                }, {
                    "url": "http://armstrong.edu",
                    "duration": 10
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /tvs/2

    + Body

            {
                "id": 2,
                "slides": [
                    {
                        "url": "http://google.com",
                        "duration": 10
                    }, {
                        "url": "http://cs.armstrong.edu",
                        "duration": 20
                    }, {
                        "url": "http://armstrong.edu",
                        "duration": 10
                    }
                ]
            }

## TV [/tvs/{tv_id}]

+ Parameters
    + tv_id (number) - ID of the TV in the form of an integer

### View a TV detail [GET]

+ Response 200 (application/json)

        {
            "id": "1",
            "slides": [
                {
                    "url": "http://google.com",
                    "duration": 10
                }, {
                    "url": "http://cs.armstrong.edu",
                    "duration": 20
                }, {
                    "url": "http://armstrong.edu",
                    "duration": 10
                }
            ]
        }