FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Smart TV Content API

Smart TV Content API is an api that allows users to choose which
content to display on connected Smart TVs.

## TVs Collection [/tvs]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "id": "1",
                "slides": [
                    {
                        "url": "http://google.com",
                        "duration": 10
                    }, {
                        "choice": "http://cs.armstrong.edu",
                        "votes": 20
                    }, {
                        "choice": "http://armstrong.edu",
                        "votes": 10
                    }
                ]
            }
        ]

### Register a New TV [POST]

You may register a new TV endpoint here. Note that the TV will be
required to point to a specific URL on startup.

+ Request (application/json)

        {
            "slides": [
                {
                    "url": "http://google.com",
                    "duration": 10
                }, {
                    "choice": "http://cs.armstrong.edu",
                    "votes": 20
                }, {
                    "choice": "http://armstrong.edu",
                    "votes": 10
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /tvs/2

    + Body

            {
                "id": 2,
                "slides": [
                    {
                        "url": "http://google.com",
                        "duration": 10
                    }, {
                        "choice": "http://cs.armstrong.edu",
                        "votes": 20
                    }, {
                        "choice": "http://armstrong.edu",
                        "votes": 10
                    }
                ]
            }